uwsgi:
  socket: 0.0.0.0:5000
  master: 1
  workers: 1
  chmod-socket: 666
  auto-procname: 1
  python-path: .
  pidfile: /tmp/uwsgi.pid
  daemonize: /home/ec2-user/uwsgi.log
  module: wsgi:application
